### ISSUE TITLE
Missing parameters on command system.gettouchscreen

### ISSUE THREAD

**Issue by bmsatierf** [cloudwalkio/cloudwalk-docs#82]
The parameters `timeout` and `variablekey` are not described under the section **Parameters**:

https://docs.cloudwalk.io/en/posxml/commands/system.gettouchscreen

**Comment by scalone** [comment]
Hey @bmsatierf isn't because those parameters belongs to system.gettouchscreenkeyboard, @williamrgt created a new instruction.
Follow the walk_framework code: https://github.com/planobe/walk_framework/blob/master/src/pos/application/walk.c#L4079-#l4112

**Comment by bmsatierf** [comment]
That is covered here:

https://github.com/cloudwalkio/cloudwalk-docs/commit/30eb3fcddfc02f0e70f90c26c97b29de7ee2345a

**Comment by davidtkelleher** [comment]
@bmsatierf actually, the parameters `timeout` and `variablekey` don't belong to this command, so the posxml example is incorrect.

I have updated that now, can you check it and close the issue if it's all good?
https://docs.cloudwalk.io/en/posxml/commands/system.gettouchscreen

@williamrgt one feedback about this command and others like it, is to use `system.getevent` instead of the current command names. It would make more sense. Just one to think about for now. Thanks.

**Comment by bmsatierf** [comment]
Thanks @davidtkelleher!
